In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [9]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array 
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [10]:
# Attributes of 2-dimensional array 
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [11]:
# Attributes of 3-dimensional array 
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 2), 3, dtype('int32'), 8, numpy.ndarray)

In [19]:
# Import pandas and create a DataFrame out of one of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2, columns=["A","B","C"])
df

A  B  C
0  1  2  3
1  4  5  6

In [14]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10,2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7,2,3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.arange(1,100,3)
array_range

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(1,10,size=(7,2))
random_array

array([[5, 2],
       [7, 1],
       [9, 6],
       [2, 1],
       [7, 1],
       [5, 7],
       [4, 9]])

In [24]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array = np.random.rand(3,5)
random_array

array([[0.18093139, 0.02476778, 0.73814517, 0.26023063, 0.30185495],
       [0.98026911, 0.67218252, 0.46024391, 0.07935539, 0.67473741],
       [0.21043571, 0.57137467, 0.181455  , 0.45698941, 0.15667346]])

In [34]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(1,10,size=(4,6))
random_array

array([[7, 4, 8, 5, 7, 3],
       [7, 8, 5, 4, 8, 8],
       [3, 6, 5, 2, 8, 6],
       [2, 5, 1, 6, 9, 1]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable
random_array = np.random.randint(1,10,size=(3,7))
random_array

array([[3, 7, 4, 9, 3, 5, 3],
       [7, 5, 9, 7, 2, 4, 9],
       [2, 9, 5, 2, 4, 7, 8]])

In [36]:
# Find the unique numbers in the array you just created
unique_num = np.unique(random_array)
unique_num

array([2, 3, 4, 5, 7, 8, 9])

In [37]:
# Find the 0'th index of the latest array you created
random_array[0][0]

3

In [38]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[3, 7, 4, 9, 3, 5, 3],
       [7, 5, 9, 7, 2, 4, 9]])

In [39]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]

array([[3, 7],
       [7, 5]])

In [43]:
# Create a random array of numbers between 0 & 10 and an array of ones
#both of size (3, 5), save them both to variables
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [46]:
ones_array = np.ones((3,5),dtype=int)
ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
# Add the two arrays together
sum_array = random_array + ones_array
sum_array

array([[10,  9,  7,  9,  8],
       [ 2,  1,  7,  7,  8],
       [ 5,  3,  8,  6,  3]])

In [48]:
# Create another array of ones of shape (5, 3)
ones_array_1 = np.ones((5,3),dtype=int)

In [54]:
# Try add the array of ones and the other most recent array together
sum_array += ones_array_1

NameError: name 'ones_array_1' is not defined

When you try the last cell, it produces an error. Why do think this is?

=> Bcoz sum_array(3,5) and ones_array(5,3) are not compatible acc to broadcast rules that states 
dimension must be equal or 1 at last.

How would you fix it?

=> Create array of same dimension 

In [55]:
# Create another array of ones of shape (3, 5)
new_ones_array = np.ones((3,5),dtype=int)
new_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [67]:
# Subtract the new array of ones from the other most recent array
sub_array = sum_array - new_ones_array
sub_array

array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [68]:
# Multiply the ones array with the latest array
mul_array = new_ones_array * sub_array
mul_array

array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [71]:
# Take the latest array to the power of 2 using '**'
mul_array ** 2

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]], dtype=int32)

In [72]:
# Do the same thing with np.square()
np.square(mul_array)

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]], dtype=int32)

In [73]:
# Find the mean of the latest array using np.mean()
np.mean(mul_array)

5.2

In [74]:
# Find the maximum of the latest array using np.max()
np.max(mul_array)

9

In [75]:
# Find the minimum of the latest array using np.min()
np.min(mul_array)

0

In [76]:
# Find the standard deviation of the latest array
np.std(mul_array)

2.6882460204874605

In [78]:
# Find the variance of the latest array
np.var(mul_array)

7.2266666666666675

In [79]:
# Reshape the latest array to (3, 5, 1)
np.reshape(mul_array,(3,5,1))

array([[[9],
        [8],
        [6],
        [8],
        [7]],

       [[1],
        [0],
        [6],
        [6],
        [7]],

       [[4],
        [2],
        [7],
        [5],
        [2]]])

In [80]:
# Transpose the latest array
mul_array.T

array([[9, 1, 4],
       [8, 0, 2],
       [6, 6, 7],
       [8, 6, 5],
       [7, 7, 2]])

What does the transpose do?

=> switches row and column of array

In [82]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_a1 = np.random.randint(0,10,size=(3,3))
random_a2 = np.random.randint(0,10,size=(3,2))

In [83]:
# Perform a dot product on the two newest arrays you created
np.dot(random_a1,random_a2)

array([[ 42,   4],
       [ 40,  18],
       [162,  93]])

In [84]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_a1 = np.random.randint(0,10,size=(4,3))
random_a2 = np.random.randint(0,10,size=(4,3))

In [85]:
# Perform a dot product on the two newest arrays you created
np.dot(random_a1,random_a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

=> Taking transpose of one of them

In [88]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(random_a1,random_a2.T)

array([[ 39,  77,  18,  60],
       [ 63, 114,  36, 105],
       [ 49, 106,  36,  79],
       [ 73, 127,   6, 104]])

In [109]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0,10,size=(4,3))
arr2 = np.random.randint(0,10,size=(4,3))
arr1, arr2

(array([[7, 7, 1],
        [5, 6, 1],
        [9, 1, 9],
        [0, 7, 0]]),
 array([[8, 5, 6],
        [9, 6, 9],
        [2, 1, 8],
        [7, 9, 6]]))

In [110]:
# Compare the two arrays with '>'
arr1 > arr2

array([[False,  True, False],
       [False, False, False],
       [ True, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

=> performs element wise comparison

In [111]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[False,  True, False],
       [False,  True, False],
       [ True,  True,  True],
       [False, False, False]])

In [112]:
# Find which elements of the first array are greater than 7
greater = arr1 > 7
arr1[greater]

array([9, 9])

In [114]:
# Which parts of each array are equal? (try using '==')
equal = arr1 == arr2
arr1[equal]

array([6, 1])

In [117]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[1, 7, 7],
       [1, 5, 6],
       [1, 9, 9],
       [0, 0, 7]])

In [118]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1,axis=1)

array([[2, 0, 1],
       [2, 0, 1],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

In [123]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr1)

6

In [124]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr1)

9

In [122]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)

array([0, 1, 0, 1], dtype=int64)

In [125]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1,axis=0)

array([3, 2, 3], dtype=int64)

In [127]:
# Create an array of normally distributed random numbers
np.random.randn(10)

array([-0.03963614, -0.53466274, -1.7884965 ,  0.35730454, -0.41453181,
        0.08019871, -0.89312027, -0.33481725,  1.56038014,  0.128551  ])

In [128]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])