In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array 
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array 
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array 
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 2), 3, dtype('int32'), 8, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2, columns=["A","B","C"])
df

A  B  C
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10,2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7,2,3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.arange(1,100,3)
array_range

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(1,10,size=(7,2))
random_array

array([[8, 3],
       [6, 1],
       [3, 9],
       [6, 4],
       [4, 3],
       [5, 1],
       [4, 7]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array = np.random.rand(3,5)
random_array

array([[0.57493217, 0.53478843, 0.39314914, 0.74365625, 0.7764969 ],
       [0.5633529 , 0.69684758, 0.03301096, 0.42427942, 0.98050737],
       [0.87893758, 0.76708464, 0.76776692, 0.43926965, 0.58396892]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(1,10,size=(4,6))
random_array

array([[7, 4, 8, 5, 7, 3],
       [7, 8, 5, 4, 8, 8],
       [3, 6, 5, 2, 8, 6],
       [2, 5, 1, 6, 9, 1]])

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable
random_array = np.random.randint(1,10,size=(3,7))
random_array

array([[3, 7, 4, 9, 3, 5, 3],
       [7, 5, 9, 7, 2, 4, 9],
       [2, 9, 5, 2, 4, 7, 8]])

In [14]:
# Find the unique numbers in the array you just created
unique_num = np.unique(random_array)
unique_num

array([2, 3, 4, 5, 7, 8, 9])

In [15]:
# Find the 0'th index of the latest array you created
random_array[0][0]

3

In [16]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[3, 7, 4, 9, 3, 5, 3],
       [7, 5, 9, 7, 2, 4, 9]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]

array([[3, 7],
       [7, 5]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
#both of size (3, 5), save them both to variables
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1]])

In [19]:
ones_array = np.ones((3,5),dtype=int)
ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
# Add the two arrays together
sum_array = random_array + ones_array
sum_array

array([[ 3,  1,  4,  2,  8],
       [ 4,  2,  6,  6, 10],
       [ 4,  6,  2, 10,  2]])

In [21]:
# Create another array of ones of shape (5, 3)
ones_array_1 = np.ones((5,3),dtype=int)

In [22]:
# Try add the array of ones and the other most recent array together
sum_array += ones_array_1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

=> Bcoz sum_array(3,5) and ones_array(5,3) are not compatible acc to broadcast rules that states 
dimension must be equal or 1 at last.

How would you fix it?

=> Create array of same dimension 

In [23]:
# Create another array of ones of shape (3, 5)
new_ones_array = np.ones((3,5),dtype=int)
new_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# Subtract the new array of ones from the other most recent array
sub_array = sum_array - new_ones_array
sub_array

array([[2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1]])

In [25]:
# Multiply the ones array with the latest array
mul_array = new_ones_array * sub_array
mul_array

array([[2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1]])

In [26]:
# Take the latest array to the power of 2 using '**'
mul_array ** 2

array([[ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81],
       [ 9, 25,  1, 81,  1]], dtype=int32)

In [27]:
# Do the same thing with np.square()
np.square(mul_array)

array([[ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81],
       [ 9, 25,  1, 81,  1]], dtype=int32)

In [28]:
# Find the mean of the latest array using np.mean()
np.mean(mul_array)

3.6666666666666665

In [29]:
# Find the maximum of the latest array using np.max()
np.max(mul_array)

9

In [30]:
# Find the minimum of the latest array using np.min()
np.min(mul_array)

0

In [31]:
# Find the standard deviation of the latest array
np.std(mul_array)

2.8205594401741574

In [32]:
# Find the variance of the latest array
np.var(mul_array)

7.955555555555557

In [33]:
# Reshape the latest array to (3, 5, 1)
np.reshape(mul_array,(3,5,1))

array([[[2],
        [0],
        [3],
        [1],
        [7]],

       [[3],
        [1],
        [5],
        [5],
        [9]],

       [[3],
        [5],
        [1],
        [9],
        [1]]])

In [34]:
# Transpose the latest array
mul_array.T

array([[2, 3, 3],
       [0, 1, 5],
       [3, 5, 1],
       [1, 5, 9],
       [7, 9, 1]])

What does the transpose do?

=> switches row and column of array

In [36]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_a1 = np.random.randint(0,10,size=(3,3))
random_a2 = np.random.randint(0,10,size=(3,2))

In [37]:
# Perform a dot product on the two newest arrays you created
np.dot(random_a1,random_a2)

array([[ 87, 161],
       [106, 174],
       [ 36,  76]])

In [38]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_a1 = np.random.randint(0,10,size=(4,3))
random_a2 = np.random.randint(0,10,size=(4,3))

In [39]:
# Perform a dot product on the two newest arrays you created
np.dot(random_a1,random_a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

=> Taking transpose of one of them

In [40]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(random_a1,random_a2.T)

array([[138, 160, 111,  90],
       [105,  98,  56,  84],
       [ 50,  60,  23,  42],
       [ 26,  34,  30,  12]])

In [41]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0,10,size=(4,3))
arr2 = np.random.randint(0,10,size=(4,3))
arr1, arr2

(array([[7, 4, 2],
        [7, 5, 2],
        [0, 2, 4],
        [2, 0, 4]]),
 array([[9, 6, 6],
        [8, 9, 9],
        [2, 6, 0],
        [3, 3, 4]]))

In [42]:
# Compare the two arrays with '>'
arr1 > arr2

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

=> performs element wise comparison

In [43]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False,  True]])

In [44]:
# Find which elements of the first array are greater than 7
greater = arr1 > 7
arr1[greater]

array([], dtype=int32)

In [45]:
# Which parts of each array are equal? (try using '==')
equal = arr1 == arr2
arr1[equal]

array([4])

In [46]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[2, 4, 7],
       [2, 5, 7],
       [0, 2, 4],
       [0, 2, 4]])

In [47]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1,axis=1)

array([[2, 1, 0],
       [2, 1, 0],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [48]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr1)

0

In [49]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr1)

6

In [50]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)

array([0, 0, 2, 2], dtype=int64)

In [51]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1,axis=0)

array([2, 3, 0], dtype=int64)

In [52]:
# Create an array of normally distributed random numbers
np.random.randn(10)

array([-0.53441645, -1.49505387, -0.78925833,  0.74371128, -0.21216142,
       -0.42686879,  0.50144833,  1.15818665,  0.25711687,  0.3145129 ])

In [53]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])